### ISSUE TITLE
null is not an object (evaluating 'MapboxGL.UserTrackingModes')

### ISSUE THREAD

**Issue by javadmohammadis** [map-ir/mapir-react-native-sdk#1]
سلام خسته نباشید

من ماژول رو نصب کردم و نمونه کدها رو هم نوشتم وی متاسفانه با این ارور مواجه میشم
null is not an object (evaluating 'MapboxGL.UserTrackingModes')
<unknown>
    
loadModuleImplementation
    require.js:321:6
guardedLoadModule
    require.js:207:36
metroRequire
    require.js:127:24
<unknown>
    SnapshotOptions.js:35:4
loadModuleImplementation
    require.js:321:6
guardedLoadModule
    require.js:207:36
metroRequire
    require.js:127:24
<unknown>
    index.js:2
loadModuleImplementation
    require.js:321:6
guardedLoadModule
    require.js:207:36
metroRequire
    require.js:127:24
<unknown>
    map.js:3
loadModuleImplementation
    require.js:321:6
guardedLoadModule
    require.js:207:36
metroRequire
    require.js:127:24
<unknown>
    App.js:11
loadModuleImplementation
    require.js:321:6
guardedLoadModule
    require.js:207:36
metroRequire
    require.js:127:24
<unknown>
    index.js:7
loadModuleImplementation
    require.js:321:6
guardedLoadModule
    require.js:199:45
metroRequire
    require.js:127:24
global code
    

نمونه کد های نوشته شده 

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, Image} from 'react-native';
import Mapir from 'mapir-react-native-sdk' 
type Props = {};
export class map extends Component<{}> {
 
    render() { 
         
        const {navigation} = this.props;
        const { navigate } = this.props.navigation;
        return (
            <View style={styles.container}>
                <Mapir
            accessToken={'api ایمیل شده رو نوشتم'}
                    zoomLevel={13}
                    centerCoordinate={[51.422548, 35.732573]}
                    style={styles.container}>
                </Mapir>
            </View>
          );
    }
};
const styles = StyleSheet.create({
   
    container: {
        flex: 1,
      } 

})
export default map;

**Comment by javadmohammadis** [comment]
حل شد، تنظیمات اندروید رو انجام نداده بود

**Comment by AliKhoshraftar** [comment]
خیلی خوشحالیم که از مپ استفاده می کنید و مستندات رو با دقت مطالعه کردید

**Comment by abbasmoosavi** [comment]
> حل شد، تنظیمات اندروید رو انجام نداده بود

داداش چطوری حلش کردی؟

**Comment by ReyhaneMasumi** [comment]
@abbasmoosavi 
سلام
با استفاده از لینک زیر می‌توانید مشکل را برطرف نمایید.
https://support.map.ir/developers/reactnative/2-1-4/examples/geolocation/

**Comment by abbasmoosavi** [comment]
@ReyhaneMasumi 
خیلی ممنونم
