### ISSUE TITLE
All the mapbox methods not working.

### ISSUE THREAD

**Issue by c0mm4nDer** [map-ir/mapir-react-native-sdk#12]
Hi.
This issue are really disappointing!
All the methods like 'flyTo', 'moveTo', 'zoomTo' and so on are undefined!
Please for fix this issue, upgrade your "@mapbox/react-native-mapbox-gl" to version 6.1.4 or higher, as soon as you can.

**Comment by hamid** [comment]
same problems.
Please fix it. I need `flyTo` method.

**Comment by ReyhaneMasumi** [comment]
Our component was upgraded to ver2.0.5 and "@mapbox/react-native-mapbox-gl" is 7.0.0. Please upgrade sdk!

**Comment by c0mm4nDer** [comment]
@ReyhaneMasumi  I think you are super busy and you haven't enough time for check this issue.

PLEASE install mapir-mapbox with:
npm install mapir-mapbox
then check MapView.js file with your (repo)[https://github.com/map-ir/mapir-mapbox/blob/master/javascript/components/MapView.js].

**Comment by ReyhaneMasumi** [comment]
Fortunately there is no difference!
https://github.com/map-ir/mapir-mapbox/blob/ver2.0.0/javascript/components/MapView.js

**Comment by c0mm4nDer** [comment]
plz check with your master repo.

**Comment by c0mm4nDer** [comment]
> 
> 
> Fortunately there is no difference!
> https://github.com/map-ir/mapir-mapbox/blob/ver2.0.0/javascript/components/MapView.js

Can you find flyTo method in there?!

**Comment by ReyhaneMasumi** [comment]
As you can see as a warning message, `flyTo` is deprecated in `<Mapir/>` component! So you can use `<Mapir.Camera/>` component! https://github.com/map-ir/mapir-mapbox/blob/master/docs/Camera.md

**Comment by c0mm4nDer** [comment]
> 
> 
> As you can see as a warning message, `flyTo` is deprecated in `<Mapir/>` component! So you can use `<Mapir.Camera/>` component! https://github.com/map-ir/mapir-mapbox/blob/master/docs/Camera.md

You're right, but `ref ` property has some problem. So I Add custom ref property to mapir-react-native-sdk/components/Camera.js. 

Anyway `<Mapir.Camera/>` component worked @ReyhaneMasumi thanks.
