### ISSUE TITLE
center cordinate & user location doesnt work

### ISSUE THREAD

**Issue by alireza107** [map-ir/mapir-react-native-sdk#14]
how can i implement user location
i give permissions `componentDidMount() {
        {
            PermissionsAndroid.requestMultiple(
                [PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
                    PermissionsAndroid.PERMISSIONS.ACCESS_COARSE_LOCATION],
                {
                    title: 'Give Location Permission',
                    message: 'App needs location permission to find your position.'
                }
            ).then(granted => {
                console.log(granted);
                resolve();
            }).catch(err => {
                console.warn(err);
                reject(err);
            });
        }
    }`
and i make true showUserLocation property but it doesnt work

**Comment by ReyhaneMasumi** [comment]
You should add this code in `AndroidManifest.xml`
```
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
   <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```
