### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by manvfx** [map-ir/mapir-react-native-sdk#17]
سلام
با توجه به آپدیت های جدید mapbox و react native و مشکلات compatible بودن بانسخه های جدید ریکت نمیخاید نسخه جدید ارایه بدید؟

**Comment by ReyhaneMasumi** [comment]
سلام
شما می‌توانید نسخه‌ی ۲.۲.۱ را دریافت نمایید که با آخرین ورژن ریکت‌نیتیو نیز سازگار است.
